### PR TITLE
Release 0.4

### PR DESCRIPTION
**Pull request by sorki**
Rendered core ChangeLog https://github.com/sorki/hnix-store/blob/release0.4/ChangeLog.md

### CODE REVIEW

**Comment by Anton-Latukha** [comment]
Looks good. But very strange.

**Comment by sorki** [comment]
I would rather not make this a multi-stage process and instead release both at once when there changes to both libs.

**Comment by Anton-Latukha** [comment]
Well, I just could be:
1. completely silent;
2. say something and be completely honest.

**Comment by Anton-Latukha** [comment]
Thanks for doing this. The old stale situation was bugging me out for several days.

**Comment by sorki** [comment]
Well be honest, I see your reasoning about this in #101 and I don't completely agree (will respond later). Provided I use a script to upload both + docs, `core` goes first and `remote` lands right after claiming support for the released core.

**Pull request merged**
